Sample_Astronaut/Models/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Sample_Astronaut.Models
{
    public class ContactViewModel
    {
        [Required(ErrorMessage = "این فیلد اجباری میباشد")]
        [MinLength(3 , ErrorMessage = "حداقل طول مجاز 3 کاراکتر میباشد")]
        [MaxLength(50,ErrorMessage = "حداکثر طول مجاز 50 کاراکتر میباشد")]
        public string Subject { get; set; }

        [Required(ErrorMessage = "این فیلد اجباری میباشد")]
        [EmailAddress(ErrorMessage = "فرمت وارد شده با ایمیل همخوانی ندارد")]
        public string Email { get; set; }

        public string Description { get; set; }

        public int Contactor { get; set; }

        public SelectList Contactors { get; set; }
    }
}

Sample_Astronaut/Models/ContactorsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sample_Astronaut.Models
{
    public class ContactorsViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }


        public ContactorsViewModel(int id , string name)
        {
            Id = id;
            Name = name;
        }
    }
}

Sample_Astronaut/Models/ErrorViewModel.cs
namespace Sample_Astronaut.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Sample_Astronaut/Models/WorksViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sample_Astronaut.Models
{
    public class WorksViewModel
    {
        public long Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string Image { get; set; }

        public WorksViewModel(long id , string name , string description , string image)
        {
            Id = id;
            Name = name;
            Description = description;
            Image = image;
        }
    }

}

Sample_Astronaut/Controllers/DownloadController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mime;
using System.Threading.Tasks;

namespace Sample_Astronaut.Controllers
{
    public class DownloadController : Controller
    {
        public FileResult Index()
        {
            var fileByte = System.IO.File.ReadAllBytes("wwwroot/ClickMe.txt");
            const string fileName = "ClickMe.txt"; //?can change Final file name
            return File(fileByte, MediaTypeNames.Text.Plain, fileName); //! .Application.zip & .Application.Pdf 
        }

        //public JavascriptResult Index()
        //{
        //    return new JavascriptResult("alert(test)"); //
        //}

        //public RedirectToActionResult Index()
        //{
        //    return RedirectToAction("Works", "Home");
        //}

        //public IActionResult Index()
        //{
        //    return new OkResult();
        //    return new BadRequestResult();
        //    return new NotFoundResult();
        //    return new NoContentResult();
        //?    return new StatusCodeResult(502); can manually enter status code
        //}
    }

    //public class JavascriptResult : ContentResult
    //{
    //    public JavascriptResult(string data)
    //    {
    //        Content = data;
    //        ContentType = "application/javascript";
    //    }
    //! can use like something done some javascript code goes run Note: (configure needed in _Layout)
    //}
}

Sample_Astronaut/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Sample_Astronaut.Data;
using Sample_Astronaut.Models;

namespace Sample_Astronaut.Controllers
{
    //? Attribute Based Route (Primary)
    //[Route("/Inventory/Packages/")]
    // localhost:4001/Inventory/Packages/Index
    public class HomeController : Controller
    {
        private readonly List<ContactorsViewModel> _contactors = new List<ContactorsViewModel>
        {
            new ContactorsViewModel(1 , "Ali"),
            new ContactorsViewModel(2 , "Milad"),
            new ContactorsViewModel(3 , "Reza")
        };

        //[Route("MyIndex")]
        //localhost:4001/Inventory/Packages/MyIndex
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet(/*"ContactPage/{id:int}/{name:}"*/)]
        //localhost:4001/Inventory/Packages/ContactPage/2/milad
        public IActionResult Contact(int id , string name)
        {
            var model = new ContactViewModel()
            {
                Contactors = new SelectList(_contactors, "Id", "Name")
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            model.Contactors = new SelectList(_contactors, "Id", "Name");

            if (!ModelState.IsValid)
            {
                ViewBag.error = "اطلاعات وارد شده صحیح نمیباشد , لطفا دوباره تلاش کنید";
                return View(model);
            }

            ModelState.Clear();
            model = new ContactViewModel
            {
                Contactors = new SelectList(_contactors, "Id", "Name")
            };
            ViewBag.Success = "پیغام شما با موفقیت ارسال شد باتشکر";
            return View(model);
        }

        public IActionResult Works()
        {
            return View();
        }

        public IActionResult WorksDetails(long id)
        {
            var work = WorksStore.GEtProjectBy(id);
            return View(work);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Sample_Astronaut/ViewComponents/WorksViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Sample_Astronaut.Data;

namespace Sample_Astronaut.ViewComponents
{
    public class WorksViewComponent :ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var Works = WorksStore.GetWorks();
            return View("_Works" , Works);
        }
    }
}

Sample_Astronaut/Views/Home/Contact.cshtml
@model Sample_Astronaut.Models.ContactViewModel
@{
    ViewData["Title"] = "Contact";
}
<div class="section-container">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="section-container-spacer text-center">
                    <h1 class="h2">03 : Contact me</h1>
                </div>

                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        @if (!string.IsNullOrEmpty(ViewBag.Success))
                        {
                            <div class="alert-success">
                                <p> @ViewBag.Success</p>
                            </div>
                        }

                        @if (!string.IsNullOrEmpty(ViewBag.error))
                        {
                            <div class="alert-danger">
                                <p> @ViewBag.error</p>
                            </div>
                        }
                        <form asp-action="Contact" class="reveal-content">
                            <div class="row">
                                <div class="col-md-7">
                                    <div class="form-group">
                                        <input type="email" class="form-control" id="email" placeholder="Email" asp-for="Email">
                                        <span style="color: red" asp-validation-for="Email"></span>
                                    </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="subject" placeholder="Subject" asp-for="Subject">
                                        <span style="color: red" asp-validation-for="Subject"></span>
                                    </div>
                                    <div class="form-group">
                                        <select class="custom-select" asp-items="Model.Contactors">
                                            <option value="0" selected="selected">مخاطب مورد نظر را انتخاب کنید</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <textarea class="form-control" rows="5" placeholder="Enter your message" asp-for="Description"></textarea>
                                        <span style="color: red" asp-validation-for="Description"></span>
                                    </div>
                                    <button type="submit" class="btn btn-default btn-lg">Send</button>
                                </div>
                                <div class="col-md-5 address-container">
                                    <ul class="list-unstyled">
                                        <li>
                                            <span class="fa-icon">
                                                <i class="fa fa-phone" aria-hidden="true"></i>
                                            </span>
                                            + 1 2 3 4 5 6 7 8
                                        </li>
                                        <li>
                                            <span class="fa-icon">
                                                <i class="fa fa-at" aria-hidden="true"></i>
                                            </span>
                                            e-mail@mail.io
                                        </li>
                                        <li>
                                            <span class="fa-icon">
                                                <i class="fa fa fa-map-marker" aria-hidden="true"></i>
                                            </span>
                                            Lorem Ipsum
                                        </li>
                                    </ul>
                                    <h3>Follow me on social networks</h3>
                                    <a href="#" title="" class="fa-icon">
                                        <i class="fa fa-facebook"></i>
                                    </a>
                                    <a href="#" title="" class="fa-icon">
                                        <i class="fa fa-twitter"></i>
                                    </a>
                                    <a href="#" title="" class="fa-icon">
                                        <i class="fa fa-linkedin"></i>
                                    </a>

                                </div>
                            </div>
                        </form>
                    </div>

                </div>


            </div>
        </div>
    </div>
</div>

<partial name="_Footer" />

Sample_Astronaut/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@section SEO
{
    <meta name="keywords" content="Index , astronaut" />
    <meta name="description" content="Index , astronaut description " />
}

<body class="minimal">
    <div class="hero-full-container background-image-container white-text-container" style="background-image: url('/assets/images/space.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="hero-full-wrapper">
                        <div class="text-content">
                            <h1>
                                Hello,<br>
                                <span id="typed-strings">
                                    <span>A Sample Astronaut Project</span>
                                    <span>Created With C#</span>
                                    <span>Asp.net Mvc dynamic</span>
                                </span>
                                <span id="typed"></span>
                            </h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<script>
    document.addEventListener("DOMContentLoaded", function (event) {
        type();
    });
</script>

Sample_Astronaut/Views/Home/Works.cshtml
@{
    ViewData["Title"] = "Works";
}

<div class="section-container">
    <div class="container">
        <div class="row">

            <div class="col-sm-8 col-sm-offset-2 section-container-spacer">
                <div class="text-center">
                    <h1 class="h2">02 : Works</h1>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum non dolor possimus rerum provident, minima sint, in quisquam amet quos obcaecati culpa velit consequatur totam nobis ullam a aspernatur fugiat!
                        Aut consectetur dolor ab.
                    </p>
                </div>
            </div>

            @await  Component.InvokeAsync("Works")

        </div>
    </div>
</div>
<partial name="_Footer" />

Sample_Astronaut/Views/Home/WorksDetails.cshtml
@model Sample_Astronaut.Models.WorksViewModel
@{
    ViewData["Title"] = "جزئیات پروزه";
}

<div class="section-container">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="section-container-spacer text-center">
                    <h1 class="h2">03 : Contact me</h1>
                </div>

                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        
                        <table class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <td>Id</td>
                                <td>Image</td>
                                <td>Name</td>
                                <td>Description</td>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>@Model.Id</td>
                                <td><img src="~/assets/images/@Model.Image" width="100px"/></td>
                                <td>@Model.Name</td>
                                <td>@Model.Description</td>
                            </tr>
                            </tbody>
                        </table>


                    </div>

                </div>


            </div>
        </div>
    </div>
</div>

<partial name="_Footer" />

Sample_Astronaut/Views/Shared/Components/Works/_Works.cshtml
@using Sample_Astronaut.Models
@model IEnumerable<Sample_Astronaut.Models.WorksViewModel>


<div id="myCarousel" class="carousel slide projects-carousel">
    <!-- Carousel items -->
    <div class="carousel-inner">
        <div class="item active">
            <div class="row">
                @foreach (var work in Model)
                {
                    <div class="col-sm-4">

                        <a asp-controller="Home" asp-action="WorksDetails" asp-route-id="@work.Id" title="" class="black-image-project-hover">
                            <img src="~/assets/images/@work.Image" alt="@work.Name" class="img-responsive">
                        </a>
                        <div class="card-container card-container-lg">
                            <h4>@work.Id</h4>
                            <h3>@work.Name</h3>
                            <p>@work.Description</p>
                            <a asp-controller="Home" asp-action="WorksDetails" asp-route-id="@work.Id" title="" class="btn btn-default">Discover</a>
                        </div>
                    </div>
                }

            </div>
            <!--/row-->
        </div>
        <!--/item-->
    </div>
</div>

Sample_Astronaut/Views/Shared/_Footer.cshtml
@{
    Layout = null;
}


<footer class="footer-container text-center">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <p>© UNTITLED</p>
            </div>
        </div>
    </div>
</footer>

Sample_Astronaut/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width,initial-scale=1" name="viewport">
    <meta content="description" name="description">
    <meta name="google" content="notranslate" />
    @RenderSection("SEO", false)
    <!-- Disable tap highlight on IE -->
    <meta name="msapplication-tap-highlight" content="no">

    <link rel="apple-touch-icon" sizes="180x180" href="~/assets/apple-icon-180x180.png">
    <link href="#" rel="icon">

    <title>Title page</title>

    <link href="~/Css/main.css" rel="stylesheet">
</head>
<header>
    <nav class="navbar  navbar-fixed-top navbar-inverse">
        <div class="container">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav ">
                    <li><a asp-controller="Home" asp-action="Index">01 : Home</a></li>
                    <li><a asp-controller="Home" asp-action="Works">02 : Works</a></li>
                    <li><a asp-controller="Home" asp-action="Contact">03 : Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
</header>

@RenderBody()

<script src="~/lib/jquery/dist/jquery.min.js"></script>
@* Validation Scripts *@

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

@* End Validation Scripts*@
<script type="text/javascript" src="~/Js/main.js"></script>
@*<scrip type ="text/javascript" src="@Url.Action("Index","Download")"></scrip>*@
@RenderSection("Scripts", false)